// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ngM0ggQWrk2UieD8BYS84ZiXDzyR1oA',
    appId: '1:424538767306:web:bdbcc7892fbaa8cc9e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    authDomain: 'aft-flutter.firebaseapp.com',
    databaseURL: 'https://aft-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'aft-flutter.appspot.com',
    measurementId: 'G-2NNGE5Y15W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKDz78TOAUIuwm5V9jfZ7qhSz3gyQCS0',
    appId: '1:424538767306:android:2ec335991972015b9e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    databaseURL: 'https://aft-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'aft-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5yLqgHzBntkqpp1J4TIF3yyHCPgp1rU',
    appId: '1:424538767306:ios:74335b14557da4009e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    databaseURL: 'https://aft-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'aft-flutter.appspot.com',
    androidClientId: '424538767306-3ltsv1j95atipd3dh06s2k69cvrn6u4l.apps.googleusercontent.com',
    iosClientId: '424538767306-9tsastoasimirfkmcc6v9m3ju5lc0q7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm5yLqgHzBntkqpp1J4TIF3yyHCPgp1rU',
    appId: '1:424538767306:ios:74335b14557da4009e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    databaseURL: 'https://aft-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'aft-flutter.appspot.com',
    androidClientId: '424538767306-3ltsv1j95atipd3dh06s2k69cvrn6u4l.apps.googleusercontent.com',
    iosClientId: '424538767306-9tsastoasimirfkmcc6v9m3ju5lc0q7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aft',
  );
}
