// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKDz78TOAUIuwm5V9jfZ7qhSz3gyQCS0',
    // appId: '1:424538767306:android:6f678b918dbdefe19e9933',
    appId: '1:424538767306:android:2ec335991972015b9e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    storageBucket: 'aft-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5yLqgHzBntkqpp1J4TIF3yyHCPgp1rU',
    appId: '1:424538767306:ios:74335b14557da4009e9933',
    messagingSenderId: '424538767306',
    projectId: 'aft-flutter',
    storageBucket: 'aft-flutter.appspot.com',
    androidClientId:
        '424538767306-ph0efa9v4jinam45lc22amdrb4fgl59d.apps.googleusercontent.com',
    iosClientId:
        '424538767306-ui51jpfah9vm7hpg30qns1boimesg13m.apps.googleusercontent.com',
    iosBundleId: 'com.example.aft',
  );
}
